apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-boilerplate
  namespace: angular-boilerplate
  labels:
    app: angular-boilerplate
spec:
  selector:
    matchLabels:
      app: angular-boilerplate
  template:
    metadata:
      labels:
        app: angular-boilerplate
    spec:
      containers:
        - name: angular-boilerplate
          image: nginx:1.17.1-alpine
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          args:
            - npm
            - run
            - start-dist-server
