apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-boilerplate
  labels:
    app: angular-boilerplate
spec:
  selector:
    matchLabels:
      app: angular-boilerplate
  template:
    metadata:
      labels:
        app: angular-boilerplate
    spec:
      containers:
        - name: angular-boilerplate
          image: keithstric/projects:latest
          imagePullPolicy: Never
