apiVersion: v1
kind: Service
metadata:
  name: angular-boilerplate-service
spec:
  selector:
    app: angular-boilerplate
  type: LoadBalancer
  ports:
    - name: angular-boilerplate-port
      protocol: TCP
      port: 8080
      targetPort: 80
